name: openfold_venv
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python==3.10
  - conda-forge::setuptools==67.4.0
  - conda-forge::pip
  - conda-forge::openmm==8.0.0
  - conda-forge::pdbfixer==1.8.1
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pytorch::pytorch==1.13.*
  - nvidia::pytorch-cuda==11.6.*
  - pip:
      - biopython==1.81
      - deepspeed==0.7.7
      - dm-tree==0.1.8
      - ml-collections==0.1.1
      - numpy==1.24.2
      - PyYAML==6.0
      - requests==2.28.2
      - scipy==1.10.1
      - tqdm==4.64.1
      - typing-extensions==4.5.0
      - lightning==2.0.0rc0
      - wandb==0.13.10
      - git+https://github.com/NVIDIA/dllogger.git
