name: openfold_venv
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python==3.10
  - conda-forge::setuptools
  - conda-forge::pip
  - conda-forge::openmm
  - conda-forge::pdbfixer
  - conda-forge::cudatoolkit==11.6.*
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2
  - pytorch::pytorch==1.13.*
  - pip:
      - biopython
      - deepspeed
      - dm-tree
      - ml-collections
      - numpy
      - PyYAML
      - requests
      - scipy
      - tqdm
      - typing-extensions
      - lightning==2.0.0rc0
      - wandb
      - git+https://github.com/NVIDIA/dllogger.git
